# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Strolling with Aman
tagline:             'A voyage to infinity.'
description:         'The personal blog of Aman Pratap Singh'
url:                 'https://blog.amanpratapsingh.in'
baseurl:             ''
paginate:            3

# About/contact
author:
name:              'Aman Pratap Sigh'
url:               'https://amanpratapsingh.in'
email:             'amanprtpsingh@gmail.com'

# # Custom vars
# version:             1.0.0
